version: "3"
services:
  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
   
  kafka:
    container_name: kafka
    image: 'bitnami/kafka:latest'
    ports:
      - '9093:9093'
    environment:
      
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
     
    